### PR TITLE
Add cube feathering simple function loop and consistency tests

### PR DESCRIPTION
**Pull request by keflavich**
Compare to:

`fourier_combine_cubes`: assumes a single kernel for the whole cube

Lots of outstanding problems:

- [ ] currently only works in memory
- [ ] needs spectral regridding prior to loop (critical!)

### CODE REVIEW

**Comment by e-koch** [comment]
I'm derailing this PR a bit to add in more basic testing before adding more of the cube functionality.

This includes:
* [x] flux recovery checks with feeding in different high vs low res data units
* [x] [structural similarity](https://scikit-image.org/docs/stable/api/skimage.metrics.html#structural-similarity) between the original and feathered data (using skimage.metrics)
* [x]  [normalized MSE estimates](https://scikit-image.org/docs/stable/api/skimage.metrics.html#normalized-root-mse) (using skimage.metrics).
* [ ] More? 

We're close to a set of tests on recovering idealized power-spectra images.

Next up is addressing the in-memory problem for cube feathering.

**Comment by e-koch** [comment]
* [ ] add deprecation for `fourier_combine_cubes` in favour of using `feather_simple_cube` everywhere

**Comment by e-koch** [comment]
@keflavich - can you have a look through the changes? This has kinda morphed into adding CI tests, so I'd proposed we merge this if no issues come up/tests pass, then address the in-memory issues for cube feathering in another PR.

**Comment by keflavich** [comment]
Yeah, sounds good to me.  Because I'm the original author, I can't approve it... so I'll go ahead and merge now.

**Pull request merged**
